spring:
  rabbitmq:
    host: 192.168.223.100 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123456 # 密码
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS