spring:
  rabbitmq:
    host: 192.168.223.100 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123456 # 密码
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后倍数等待时间 下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大失败重试次数
    publisher-confirm-type: correlated # 开启publisher confirm机制
    publisher-returns: true # 开启publisher return机制
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    org.springframework.amqp: debug